// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID
	CreateTime time.Time
	UpdateTime time.Time
	Username   string
	ApiKey     string
}
