// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID
	Createtime time.Time
	Updatetime time.Time
	Username   string
}
