// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID         uuid.UUID
	CreateTime time.Time
	UpdateTime time.Time
	Url        string
	Name       string
	UserID     uuid.UUID
	FetchTime  sql.NullTime
}

type Follow struct {
	ID         uuid.UUID
	CreateTime time.Time
	UpdateTime time.Time
	UserID     uuid.UUID
	FeedID     uuid.UUID
}

type User struct {
	ID         uuid.UUID
	CreateTime time.Time
	UpdateTime time.Time
	Username   string
	ApiKey     string
}
