// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, create_time, update_time, publish_date, url, feed_id, title, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, create_time, update_time, publish_date, url, feed_id, title, description
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreateTime  time.Time
	UpdateTime  time.Time
	PublishDate time.Time
	Url         string
	FeedID      uuid.UUID
	Title       string
	Description sql.NullString
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreateTime,
		arg.UpdateTime,
		arg.PublishDate,
		arg.Url,
		arg.FeedID,
		arg.Title,
		arg.Description,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreateTime,
		&i.UpdateTime,
		&i.PublishDate,
		&i.Url,
		&i.FeedID,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const getUserPosts = `-- name: GetUserPosts :many
SELECT posts.id, posts.create_time, posts.update_time, posts.publish_date, posts.url, posts.feed_id, posts.title, posts.description from posts
JOIN follows ON posts.feed_id = follows.feed_id
WHERE follows.user_id = $1
ORDER BY posts.publish_date DESC
LIMIT $2
`

type GetUserPostsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetUserPosts(ctx context.Context, arg GetUserPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getUserPosts, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreateTime,
			&i.UpdateTime,
			&i.PublishDate,
			&i.Url,
			&i.FeedID,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
