// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, createTime, updateTime, username) 
VALUES ($1, $2, $3, $4)
RETURNING id, createtime, updatetime, username
`

type CreateUserParams struct {
	ID         uuid.UUID
	Createtime time.Time
	Updatetime time.Time
	Username   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Createtime,
		arg.Updatetime,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Createtime,
		&i.Updatetime,
		&i.Username,
	)
	return i, err
}
